# Generated by Django 3.1.7 on 2021-05-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_auto_20210503_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='snippets',
            new_name='snippet',
        ),
    ]
